export const ADD_TODO = "ADD_TODO";
export const TOGGLE_TODO = "TOGGLE_TODO";
export const SET_FILTER = "SET_FILTER";

export const ADD_USER_INFO = "ADD_USER_INFO";
export const COMPARE_HEIGHT = "COMPARE_HEIGHT";
export const HANDLE_SELECTED_FILES = "HANDLE_SELECTED_FILES";

export const DETERMINE_ITEM = "DETERMINE_ITEM";

export const ADD_DIRECTORY_TREE = "ADD_DIRECTORY_TREE";
export const HAVE_LOADED_DIRECTORY_TREE = "HAVE_LOADED_DIRECTORY_TREE";
export const HANDLE_DOCUMENT_TABLE_DATA = "HANDLE_DOCUMENT_TABLE_DATA";

export const HANDLE_NEW_FOLDER_MODAL = "HANDLE_NEW_FOLDER_MODAL";

export const HANDLE_SELECTED_TREE_NODE = "HANDLE_SELECTED_TREE_NODE";

export const HANDLE_SELECTED_DIRECTORY = "HANDLE_SELECTED_DIRECTORY";
