export const ADD_TODO = "ADD_TODO";
export const TOGGLE_TODO = "TOGGLE_TODO";
export const SET_FILTER = "SET_FILTER";

export const ADD_USER_INFO = "ADD_USER_INFO";
export const COMPARE_HEIGHT = "COMPARE_HEIGHT";
export const HANDLE_SELECTED_FILES = "HANDLE_SELECTED_FILES";

export const DETERMINE_ITEM = "DETERMINE_ITEM";